[package]
name = "regexsolver"
version = "1.0.0"
edition = "2024"
authors = ["Alexandre van Beurden"]
repository = "https://github.com/RegexSolver/regexsolver"
license = "MIT"
keywords = ["automaton", "intersection", "union", "difference", "regex"]
categories = ["text-processing", "mathematics", "algorithms"]
description = "High-performance Rust library for building, combining, and analyzing regular expressions and finite automata"
readme = "README.md"

[dependencies]
nohash-hasher = "0.2"
ahash = "0.8.11"
regex-syntax = "0.8.5"
regex-charclass = { version = "1.0.3" }
rayon = { version = "1.10.0", optional = true }
bit-set = "0.8.0"
indexmap = "2.13.0"

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1"
regex = "1.10.3"

[[bench]]
name = "operations"
harness = false
